<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-04T12:31:56 IST" name="Suite" finished-at="2025-05-04T12:33:00 IST" duration-ms="63978">
    <groups>
      <group name="E2E Testing">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" name="submitOrder" class="Learnings.Tests.SubmitOrderTest"/>
      </group> <!-- E2E Testing -->
    </groups>
    <test started-at="2025-05-04T12:31:56 IST" name="Error Validations" finished-at="2025-05-04T12:32:20 IST" duration-ms="23279">
      <class name="Learnings.Tests.ErrorValidations">
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:31:56 IST" name="lounchApplication" finished-at="2025-05-04T12:32:01 IST" duration-ms="5148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="ErrorValidationsTest()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:01 IST" name="ErrorValidationsTest" finished-at="2025-05-04T12:32:03 IST" duration-ms="1288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidationsTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:03 IST" name="tearDown" finished-at="2025-05-04T12:32:03 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:03 IST" name="lounchApplication" finished-at="2025-05-04T12:32:05 IST" duration-ms="1926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method retried="true" signature="productValidationCheck()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:05 IST" name="productValidationCheck" finished-at="2025-05-04T12:32:09 IST" duration-ms="4379" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Learnings.Tests.ErrorValidations.productValidationCheck(ErrorValidations.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidationCheck -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:09 IST" name="tearDown" finished-at="2025-05-04T12:32:09 IST" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:09 IST" name="lounchApplication" finished-at="2025-05-04T12:32:16 IST" duration-ms="6146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="productValidationCheck()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:16 IST" name="productValidationCheck" finished-at="2025-05-04T12:32:19 IST" duration-ms="3499" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Learnings.Tests.ErrorValidations.productValidationCheck(ErrorValidations.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidationCheck -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.ErrorValidations@31ea9581]" started-at="2025-05-04T12:32:19 IST" name="tearDown" finished-at="2025-05-04T12:32:20 IST" duration-ms="154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Learnings.Tests.ErrorValidations -->
    </test> <!-- Error Validations -->
    <test started-at="2025-05-04T12:32:20 IST" name="Tests" finished-at="2025-05-04T12:33:00 IST" duration-ms="40068">
      <class name="Learnings.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:20 IST" name="lounchApplication" finished-at="2025-05-04T12:32:25 IST" duration-ms="4493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:25 IST" name="submitOrder" data-provider="getData" finished-at="2025-05-04T12:32:36 IST" duration-ms="11028" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{passWord=!123weSDF, userName=nikhil1997@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:36 IST" name="tearDown" finished-at="2025-05-04T12:32:36 IST" duration-ms="265" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:36 IST" name="lounchApplication" finished-at="2025-05-04T12:32:40 IST" duration-ms="3763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:40 IST" name="submitOrder" data-provider="getData" finished-at="2025-05-04T12:32:54 IST" duration-ms="14024" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{passWord=#345rtFGH, userName=mayur1995@gmail.com, productName=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:54 IST" name="tearDown" finished-at="2025-05-04T12:32:54 IST" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lounchApplication()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:54 IST" name="lounchApplication" finished-at="2025-05-04T12:32:59 IST" duration-ms="4310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lounchApplication -->
        <test-method signature="MyOrders()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:32:59 IST" name="MyOrders" finished-at="2025-05-04T12:33:00 IST" depends-on-methods="Learnings.Tests.SubmitOrderTest.submitOrder" duration-ms="1290" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Learnings.Tests.SubmitOrderTest.MyOrders(SubmitOrderTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyOrders -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Learnings.Tests.SubmitOrderTest@60f00693]" started-at="2025-05-04T12:33:00 IST" name="tearDown" finished-at="2025-05-04T12:33:00 IST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Learnings.Tests.SubmitOrderTest -->
    </test> <!-- Tests -->
  </suite> <!-- Suite -->
</testng-results>
